name: CD Deploy with Self-Hosted Runner

on:
  workflow_run: # Triggered manually from the GitHub Actions UI
    workflows: ["CI Docker Build and Push Locally"]
    types: 
      -completed

jobs:
  deploy:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Pull Docker image from Docker Hub
      - name: Pull Docker image
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull otniel217/cicd-pipeline:latest
          sudo docker images # Verify the image is pulled

      # Step 3: Stop and remove the existing container (if any)
      - name: Stop and remove existing container
        run: |
          sudo docker stop app || true
          sudo docker rm app || true

      # Step 4: Deploy the new container
      - name: Run new container
        run: |
          sudo docker run -d --name app -p 3001:3001 otniel217/cicd-pipeline:latest
          
      # Optional Step: Check if the container is running
      - name: Verify the container is running
        run: |
          sudo docker ps -a # List all containers to verify if it's running
